setGeneric("qaReport", function(object, ...) standardGeneric("qaReport"))
setGeneric("getDesign", function(object) standardGeneric("getDesign"))
setGeneric("getTarget", function(object) standardGeneric("getTarget"))
setGeneric("getCovariates", function(object) standardGeneric("getCovariates"))
setGeneric("getIntIndex", function(object) standardGeneric("getIntIndex"))
setGeneric("getContrast", function(object) standardGeneric("getContrast"))
setGeneric("getCompare1", function(object) standardGeneric("getCompare1"))
setGeneric("getCompare2", function(object) standardGeneric("getCompare2"))
setGeneric("getLevel", function(object) standardGeneric("getLevel"))
setGeneric("getInteraction", function(object) standardGeneric("getInteraction"))
setGeneric("getID", function(object) standardGeneric("getID"))
setGeneric("getFC", function(object) standardGeneric("getFC"))
setGeneric("getF", function(object) standardGeneric("getF"))
setGeneric("getP", function(object) standardGeneric("getP"))
setGeneric("getAdjP", function(object) standardGeneric("getAdjP"))
setGeneric("regressionMethod", function(object) standardGeneric("regressionMethod"))
setGeneric("adjustment", function(object) standardGeneric("adjustment"))
setGeneric("getIndex", function(object) standardGeneric("getIndex"))
setGeneric("getPCutoff", function(object) standardGeneric("getPCutoff"))
setGeneric("getFCCutoff", function(object) standardGeneric("getFCCutoff"))
setGeneric("getFileName", function(object) standardGeneric("getFileName"))
setGeneric("getAnnotation", function(object) standardGeneric("getAnnotation"))
setGeneric("getNormalizationMethod", function(object) standardGeneric("getNormalizationMethod"))
setGeneric("getFilterMethod", function(object) standardGeneric("getFilterMethod"))
setGeneric("Sort", function(x, ...) standardGeneric("Sort"))
setGeneric("Output2HTML", function(object, ...) standardGeneric("Output2HTML"))
setGeneric("getLength", function(object) standardGeneric("getLength"))